### PR TITLE
Improve elevenlabsSynth with options for voice_id

### PR DESCRIPTION
**Pull request by Catharsis68**
This PR improves the `synthElevenlabs` function and adds also the possibility to provide the `voice_id` via `options`

### CODE REVIEW

**Comment by davehorton** [comment]
I believe we achieved this with `synthesizer.options`

**Comment by Catharsis68** [comment]
@davehorton  yes you are right, the `synthesizer.options` property can be used for all the elevenlabs configuration.
The only thing that is missing, is that we can also provide the `voice_id` via options. Right now the voice get's always used from the credentials. Since it's part of the `path` and not the body, `...opts` is not enough

**Comment by xquanluu** [comment]
Hi @Catharsis68 the voiceID is taken from synthesizer.voice, I dont think we need to provide voice_id in options or may be I missed something

**Comment by xquanluu** [comment]
Now I understand that you might want to override all setup that have been done through speech credential.

Could you follow the same approach we have for microsoft at feature server instead of speech uitils, so that we have only 1 common place where we manipulate synthesizer data, it's easier for developer later know where should I need to modify the code:

https://github.com/jambonz/jambonz-feature-server/blob/main/lib/tasks/say.js#L82

Could you please move the code here to feature server instead. that would be great

**Pull request closed without merging**
