### PR TITLE
Improve handling of TTS cache by adding the file extension to the cac…

### PR DESCRIPTION
**Pull request by Catharsis68**
Improve handling of TTS cache by adding the file extension to the cache key.

This PR solves an issue that occurs when when the file extension of the TTS files changes from `.r8` to `.mp3` and vice versa due to enable / disable streaming or change JAMBONES_TTS_TRIM_SILENCE

Right now this leads to corrupted audio data retrieved from the cache.

This PR is introducing a new cache key including the file extension.
With this - the data in the cache is always valid based on the cluster configuration

### CODE REVIEW

**Comment by xquanluu** [comment]
Thanks @Catharsis68  for the PR.

Hi @davehorton I love this PR. Look good to me, no comment from me.

**Comment by davehorton** [comment]
when I run the tests locally they fail
```
# Azure SSML tests
{"level":30,"time":1716560787989,"pid":96047,"hostname":"daveh-macbook-pro.local","msg":"tts rtt time for 189 chars on microsoft: 312"}
ok 11 successfully synthesized microsoft audio to /tmp/tts-51f9721c26e23256c8e4b4f6c3a28cad4a5ad767.r8
{"level":30,"time":1716560788239,"pid":96047,"hostname":"daveh-macbook-pro.local","msg":"tts rtt time for 189 chars on microsoft: 244"}
not ok 12 successfully retrieved microsoft audio from cache /tmp/tts-d1ae666c0f66a66044d0b35987ab6d8c8032ce21.r8
  ---
    operator: ok
    expected: true
    actual:   false
    at: Test.<anonymous> (/Users/dhorton/beachdog-enterprises/beachdog-networks/git/jambones.org/git/utils/speech-utils/test/synth.js:283:7)
    stack: |-
      Error: successfully retrieved microsoft audio from cache /tmp/tts-d1ae666c0f66a66044d0b35987ab6d8c8032ce21.r8
          at Test.assert [as _assert] (/Users/dhorton/beachdog-enterprises/beachdog-networks/git/jambones.org/git/utils/speech-utils/node_modules/tape/lib/test.js:479:48)
          at Test.assert (/Users/dhorton/beachdog-enterprises/beachdog-networks/git/jambones.org/git/utils/speech-utils/node_modules/tape/lib/test.js:616:7)
          at Test.<anonymous> (/Users/dhorton/beachdog-enterprises/beachdog-networks/git/jambones.org/git/utils/speech-utils/test/synth.js:283:7)
  ...
```

**Comment by Catharsis68** [comment]
@davehorton  When I'm running the test locally, including Azure - they are passing

In addition I added a cache namespace for "custom" vendors 

Screenshot from 2024-05-27 11-03-47

**Comment by davehorton** [comment]
ok, great.  Let me look into why my tests are failing..

**Comment by davehorton** [comment]
can you rebase to main?  My tests _do_ pass, the issue was that I was trying to run one test that I did not have credentials for

**Comment by Catharsis68** [comment]
@davehorton  done. And I've put the `HTTP_TIMEOUT` into the existing `config` file and deleted `constants` again

**Review by davehorton — APPROVED** [review]

**Comment by davehorton** [comment]
merged in v0.1.2

**Comment by davehorton** [comment]
in the future please run `npm run jslint` before making PR

**Pull request merged**
